spring.application.name=Kozmeticki salon

# Port na kojem se aplikacija pokrece
server.port=8080

# Thymeleaf podesavanja
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Ispravno prikazivanje nasih slova (c, c, s, d, z)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Poruke o greskama u razvojnom rezimu
server.error.include-message=always
server.error.include-binding-errors=always
